name: Makefile CI

on:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run make
      run: make
      
    - name: Clean
      run: make clean

