name: Update Homebrew & Nix

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
      sha256: ${{ steps.calc_sha.outputs.sha256 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set release version from tag
        id: set_version
        run: echo "release_version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Download release tarball
        run: wget https://github.com/jmattaa/laser/archive/${{ steps.set_version.outputs.release_version }}.tar.gz -O laser.tar.gz

      - name: Calculate SHA256
        id: calc_sha
        run: echo "sha256=$(sha256sum laser.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

  homebrew:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout Homebrew repo
        uses: actions/checkout@v3
        with:
          repository: jmattaa/homebrew-laser
          ref: main

      - name: Update Homebrew formula
        run: ./update-homebrew.sh "${{ needs.prepare.outputs.release_version }}" "${{ needs.prepare.outputs.sha256 }}"

  nix:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Nix
        uses: cachix/install-nix-action@v24

      - name: Update flake.nix
        run: ./update-flake.sh "${{ needs.prepare.outputs.release_version }}"

